# Project: E OU NAO
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "E\ OU\ NAO.o"
LINKOBJ  = "E OU NAO.o"
LIBS     = -L"C:/Users/aluno.C305-CAXLAB-024/Documents/Dev-Cpp/MinGW64/lib" -L"C:/Users/aluno.C305-CAXLAB-024/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/aluno.C305-CAXLAB-024/Documents/Dev-Cpp/MinGW64/include" -I"C:/Users/aluno.C305-CAXLAB-024/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/aluno.C305-CAXLAB-024/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/aluno.C305-CAXLAB-024/Documents/Dev-Cpp/MinGW64/include" -I"C:/Users/aluno.C305-CAXLAB-024/Documents/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/aluno.C305-CAXLAB-024/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/aluno.C305-CAXLAB-024/Documents/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "E OU NAO.exe"
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

"E\ OU\ NAO.o": E\ OU\ NAO.c
	$(CC) -c "E OU NAO.c" -o "E OU NAO.o" $(CFLAGS)
